### ISSUE TITLE
"unknown configs.Cgroup field 'AllowAllDevices' in struct literal" when trying to build compose2kube

### ISSUE THREAD

**Issue by jmlrt** [kelseyhightower/compose2kube#14]
Hi,
When I try to build compose2kube, I get the following error:

```
$ pwd
/home/jmlrt/work/src/github.com/kelseyhightower/compose2kube
$ go build . 
# k8s.io/kubernetes/pkg/util
../../../k8s.io/kubernetes/pkg/util/resource_container_linux.go:37: unknown configs.Cgroup field 'AllowAllDevices' in struct literal
```

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
$ go version
go version go1.5.1 linux/amd64
```

**Comment by kevinpgrant** [comment]
Same here

``` bash
  $ go build .
  # github.com/docker/libcompose/project
  ../../golang/src/github.com/docker/libcompose/project/utils.go:54: undefined: runconfig.IpcMode
  # k8s.io/kubernetes/pkg/util
  ../../golang/src/k8s.io/kubernetes/pkg/util/resource_container_linux.go:37: unknown configs.Cgroup field 'AllowAllDevices' in struct literal
  $ cat /etc/redhat-release 
  Fedora release 22 (Twenty Two)
  $ go version
  go version go1.5.3 linux/amd64
```

compose2kube revision aeecc01

----- more detail:

tried to build this on mac (yosemite 10.10.3) and don't get the configs.Cgroup error. I havent resolved the other issue, but that appears to be docker/libcompose related.

```
$ go build . # fails, need to install some deps...
$ go get k8s.io/kubernetes/pkg/api
$ go get github.com/docker/libcompose/project
# github.com/docker/libcompose/project
../go/src/github.com/docker/libcompose/project/utils.go:54: undefined: runconfig.IpcMode
$ go build .
# github.com/docker/libcompose/project
../go/src/github.com/docker/libcompose/project/utils.go:54: undefined: runconfig.IpcMode
```

**Comment by oviis** [comment]
---

it seams that it is the same issue also for the hole kubernetes/util package on Linux Mint 17, when i try to access it, as follows:

 k8s.io/kubernetes/pkg/util
../../../k8s.io/kubernetes/pkg/util/resource_container_linux.go:37: unknown configs.Cgroup field 'AllowAllDevices' in struct literal
 k8s.io/kubernetes/pkg/util/parsers
../../../k8s.io/kubernetes/pkg/util/parsers/parsers.go:30: undefined: parsers.ParseRepositoryTag
 github.com/kubernetes/kubernetes/pkg/util
../../kubernetes/kubernetes/pkg/util/resource_container_linux.go:37: unknown configs.Cgroup field 'AllowAllDevices' in struct literal

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ovi/goWorkspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by kramos** [comment]
$ winpty docker run -it golang go version
go version go1.5.3 linux/amd64

$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoPath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

$ winpty docker run -it golang bash
root@bdff8d7c91e8:/go# git clone https://github.com/kelseyhightower/compose2kube.git
Cloning into 'compose2kube'...
remote: Counting objects: 39, done.
remote: Total 39 (delta 0), reused 0 (delta 0), pack-reused 39
Unpacking objects: 100% (39/39), done.
Checking connectivity... done.
root@bdff8d7c91e8:/go# cd compose2kube/
root@bdff8d7c91e8:/go/compose2kube# export GOBIN=$GOPATH/bin
root@bdff8d7c91e8:/go/compose2kube# export PATH=$PATH:$GOBIN
root@bdff8d7c91e8:/go/compose2kube# go get ./...
# github.com/docker/libcompose/project
../src/github.com/docker/libcompose/project/utils.go:54: undefined: runconfig.IpcMode
root@bdff8d7c91e8:/go/compose2kube# go build .
# github.com/docker/libcompose/project
../src/github.com/docker/libcompose/project/utils.go:54: undefined: runconfig.IpcMode
root@bdff8d7c91e8:/go/compose2kube#
