### ISSUE TITLE
Fixing compilation issues with new libcompose

### ISSUE THREAD

**Issue by strus38** [kelseyhightower/compose2kube#20]
Trying to use this project for my own docker-compose file, I noticed the main.go file was not more compiling with the latest libcompose.

So, here is a fix for the compilation issues (see attached diff file)
[diff.txt](https://github.com/kelseyhightower/compose2kube/files/293217/diff.txt)

However, it seems to have the following issues:
- Ports are not fixed by the code above if they are surounded with quotes ... removing quotes make it work or adding 1 line to remove quotes (as you want)
- 'environment' tags are not taken
- 'links' tags are not taken
- 'command' tags are not taken.

Is there any plan to add that?
Thanks...

**Comment by strus38** [comment]
And since I wanted to learn a little bit of Golang ... I have completed the main.go to add capabilities:
- update Ports
- 'environment', 'command' and 'volumes' tags...
  The files are generated correctly. To be proven on some other docker-compose files.

[diff.txt](https://github.com/kelseyhightower/compose2kube/files/293627/diff.txt)

**Comment by fkautz** [comment]
The build break should be fixed in master. I noticed you have some new info you added to PR #21 to populate the spec with. I'll review your patch soon and try to merge them in. Thanks for submitting!
