### ISSUE TITLE
Build fails with "cannot range over service.Volumes"

### ISSUE THREAD

**Issue by cmachler** [kelseyhightower/compose2kube#34]
When trying to build it fails with the below output:

`./main.go:134: cannot range over service.Volumes (type "github.com/docker/libcompose/yaml".Volumes)
`
go version go1.6.2 linux/amd64

**Comment by germanramos** [comment]
This bug is fixed im my fork among many other features: https://github.com/germanramos/compose2kube

I am waiting for the pull request to be accepted

**Comment by cmachler** [comment]
Build works now with @germanramos pull request merge #33.

Thanks!
